### ISSUE TITLE
cant locate python3

### ISSUE THREAD

**Issue by dhinesh993** [Deadpool2000/Termux-GUI#3]
~ $ apt install python3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3

am getting ths

**Comment by Deadpool2000** [comment]
Just run 'apt install python'
and 'python gui.py'

**Comment by dhinesh993** [comment]
python gui.py
python: can't open file '/data/data/com.termux/files/home/gui.py': [Errno 2] No such file or directory


ths is the result bro🥺🥺🥺

**Comment by Deadpool2000** [comment]
1) cd Termux-GUI
2) python gui.py

Run above commands one by one

**Comment by dhinesh993** [comment]
cd Termux-GUI
bash: cd: Termux-GUI: No such file or directory
~ $ python gui.py
python: can't open file '/data/data/com.termux/files/home/gui.py': [Errno 2] No such file or directory

ths is the result bro

**Comment by Deadpool2000** [comment]
just follow installation process properly
